version: "3.9"
services:
  www:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:db"
    env_file:
      - ./docker/env.dev
    volumes:
      - ./app/:/opt/app/cavedb/
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=cavedb
      - POSTGRES_PASSWORD=cavedb
      - POSTGRES_DB=cavedb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./utils/test_data.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
