# Generated by Django 4.0.2 on 2022-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavingbody",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
