# Generated by Django 4.0.3 on 2022-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cave",
            name="references",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cavesystem",
            name="references",
            field=models.TextField(blank=True),
        ),
    ]
