# Generated by Django 4.0.2 on 2022-03-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cave",
            name="code",
        ),
        migrations.RemoveField(
            model_name="country",
            name="code",
        ),
    ]
