# Generated by Django 4.0.3 on 2022-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_cave_references_cavesystem_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
