# Generated by Django 4.0.2 on 2022-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_remove_cave_code_remove_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="abbreviation",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="abbreviation",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
