# Generated by Django 4.0.3 on 2022-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_organisation_description_alter_club_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cave",
            name="resources",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cavesystem",
            name="resources",
            field=models.TextField(blank=True),
        ),
    ]
