# Generated by Django 4.0.2 on 2022-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_alter_cave_length_alter_cavesystem_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cave",
            name="length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="length in meters"
            ),
        ),
        migrations.AlterField(
            model_name="cavesystem",
            name="length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="length in meters"
            ),
        ),
    ]
