# Generated by Django 4.0.2 on 2022-03-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_alter_cave_length_alter_cavesystem_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cave",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="length in metres",
            ),
        ),
        migrations.AlterField(
            model_name="cavesystem",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="length in metres",
            ),
        ),
    ]
