# Generated by Django 4.0.3 on 2022-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_alter_cave_length_alter_cavesystem_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cave",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="length in kilometres",
            ),
        ),
        migrations.AlterField(
            model_name="cavesystem",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="length in kilometres",
            ),
        ),
    ]
