# Generated by Django 4.0.3 on 2022-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_alter_cave_length_alter_cavesystem_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="cave",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cavesystem",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
