# Generated by Django 4.0.3 on 2022-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_cave_slug_cavesystem_slug_club_slug_country_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cave",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="cavesystem",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
